"""empty message

Revision ID: 8878298b05cc
Revises: 
Create Date: 2018-07-12 09:48:47.055988

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8878298b05cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinatura',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_entidade', sa.Integer(), nullable=True),
                    sa.Column('id_pacote_informacao', sa.Integer(), nullable=True),
                    sa.Column('data_compra', sa.String(length=10), nullable=True),
                    sa.Column('validade', sa.String(length=10), nullable=True),
                    sa.Column('preco_compra', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('endereco',
                    sa.Column('codlocal', sa.Integer(), nullable=False),
                    sa.Column('local1', sa.String(length=100), nullable=True),
                    sa.Column('local2', sa.String(length=100), nullable=True),
                    sa.Column('complemento', sa.String(length=100), nullable=True),
                    sa.Column('numero', sa.String(length=10), nullable=True),
                    sa.Column('bairro', sa.String(length=20), nullable=True),
                    sa.Column('latitude', sa.String(length=30), nullable=True),
                    sa.Column('longitude', sa.String(length=30), nullable=True),
                    sa.PrimaryKeyConstraint('codlocal')
                    )
    op.create_table('enderecoEntidade',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rua', sa.String(length=35), nullable=True),
                    sa.Column('bairro', sa.String(length=30), nullable=True),
                    sa.Column('cidade', sa.String(length=30), nullable=True),
                    sa.Column('estado', sa.String(length=35), nullable=True),
                    sa.Column('numero', sa.Integer(), nullable=True),
                    sa.Column('cep', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('pacote_informacao',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome_pacote', sa.String(length=30), nullable=True),
                    sa.Column('tipo_entidade', sa.Integer(), nullable=True),
                    sa.Column('ano_pacote', sa.String(length=10), nullable=True),
                    sa.Column('duracao', sa.String(length=10), nullable=True),
                    sa.Column('descricao', sa.String(length=50), nullable=True),
                    sa.Column('valor', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sugestao',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_entidade', sa.Integer(), nullable=True),
                    sa.Column('mensagem', sa.String(length=150), nullable=True),
                    sa.Column('data', sa.String(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('usuario',
                    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.Column('email', sa.String(length=40), nullable=True),
                    sa.Column('password', sa.String(length=16), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('acidente',
                    sa.Column('codacidente', sa.Integer(), nullable=False),
                    sa.Column('data_abertura', sa.String(length=20), nullable=True),
                    sa.Column('hora_abertura', sa.String(length=20), nullable=True),
                    sa.Column('tipo_ocorrencia', sa.String(length=45), nullable=True),
                    sa.Column('quantidade_vitimas', sa.String(length=5), nullable=True),
                    sa.Column('descricao', sa.String(length=200), nullable=True),
                    sa.Column('endereco_codlocal', sa.Integer(), nullable=True),
                    sa.Column('tipo', sa.String(length=45), nullable=True),
                    sa.ForeignKeyConstraint(['endereco_codlocal'], ['endereco.codlocal'], ),
                    sa.PrimaryKeyConstraint('codacidente')
                    )
    op.create_table('entidade',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cnpj', sa.String(length=14), nullable=True),
                    sa.Column('estado', sa.Boolean(), nullable=True),
                    sa.Column('telefone', sa.Integer(), nullable=True),
                    sa.Column('tipo_entidade', sa.Integer(), nullable=True),
                    sa.Column('razao_social', sa.String(length=50), nullable=True),
                    sa.Column('id_endereco', sa.Integer(), nullable=True),
                    sa.Column('id_usuario', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id_endereco'], ['enderecoEntidade.id'], ),
                    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('cnpj')
                    )
    op.create_table('equipamento_fiscalizacao',
                    sa.Column('codequip', sa.Integer(), nullable=False),
                    sa.Column('equipamento', sa.String(length=100), nullable=True),
                    sa.Column('velocidade_regulamentada', sa.String(length=5), nullable=True),
                    sa.Column('endereco_codlocal', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['endereco_codlocal'], ['endereco.codlocal'], ),
                    sa.PrimaryKeyConstraint('codequip')
                    )
    op.create_table('registro_infracao',
                    sa.Column('codregistro', sa.Integer(), nullable=False),
                    sa.Column('data_infracao', sa.String(length=45), nullable=True),
                    sa.Column('hora_infracao', sa.String(length=10), nullable=True),
                    sa.Column('data_implantacao', sa.String(length=45), nullable=True),
                    sa.Column('agente_equipamento', sa.String(length=45), nullable=True),
                    sa.Column('infracao_codinfracao', sa.Integer(), nullable=True),
                    sa.Column('descricaoinfracao', sa.String(length=300), nullable=True),
                    sa.Column('amparolegal', sa.String(length=45), nullable=True),
                    sa.Column('endereco_codlocal', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['endereco_codlocal'], ['endereco.codlocal'], ),
                    sa.PrimaryKeyConstraint('codregistro')

    )
    op.create_table('semaforo',
                    sa.Column('codsemaforo', sa.Integer(), nullable=False),
                    sa.Column('funcionamento', sa.String(length=45), nullable=True),
                    sa.Column('sinalsonoro', sa.String(length=45), nullable=True),
                    sa.Column('sinalizadorciclista', sa.String(length=145), nullable=True),
                    sa.Column('utilizacao', sa.String(length=45), nullable=True),
                    sa.Column('endereco_codlocal', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['endereco_codlocal'], ['endereco.codlocal'], ),
                    sa.PrimaryKeyConstraint('codsemaforo')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semaforo')
    op.drop_table('registro_infracao')
    op.drop_table('equipamento_fiscalizacao')
    op.drop_table('entidade')
    op.drop_table('acidente')
    op.drop_table('usuario')
    op.drop_table('sugestao')
    op.drop_table('pacote_informacao')
    op.drop_table('infracao')
    op.drop_table('enderecoEntidade')
    op.drop_table('endereco')
    op.drop_table('assinatura')
    # ### end Alembic commands ###
